name: MyFirstWorkflow
on:
  push:
    branches: 
      - main
  workflow_dispatch:
jobs:
  MyFirstJob:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.5
